var gameScoreOrderMap = {
  'catch_dot': 1,
  'find_dot': 1,
  'spot_dot': 1,
  'speed_clicker': -1,
  'reflector': 1,
  'order_order': 1,
  'focus': 1,
  'tapper': -1,
  'alphabet_order': 1,
  'recall_rumble': 1,
  'speed_swipe': 1,
  'react_right': 1,
  'spot_out': 1,
  'bored': 1,
};
